#!/bin/bash

#  PrestoPRIME  LTFSArchiver
#  Version: 1.0 Beta
#  Authors: L. Savio, L. Boch, R. Borgotallo
#
#  Copyritght (C) 2011-2012 RAI – Radiotelevisione Italiana <cr_segreteria@rai.it>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

. $CFGFILE

function get_parameter()
{
echo $PARM | tr '&' '\n' | grep "^$1=" | sed 's/.*=//' | sed 's/\\//'
}

function geterror()
{
response=( `$CMD_DB "SELECT status,errorcode,errordescription FROM requests WHERE uuid = '$taskid';" | head -1 | tr '|' ' '` )
if [ -z "$response" ]; then
	message="400\t$taskid doesn't exist"
else
	if [ ${response[0]} == "fallout" ]; then
		message="200\t${response[1]}\t"
		for ((midx=2; midx<${#response[@]}; midx++)) ]; do
			message=$message' '${response[$midx]}
		done
	else
		message="400\t$taskid is not in fallout status"
	fi
fi
}


function output_text
{
echo 'Content-Type: text/plain'
echo ''
echo -e $message
}

# Script starts here
PARM=$QUERY_STRING
taskid=$( get_parameter TaskID )
if [ -z $taskid ]; then
	#message="Empty TaskID supplied"
	message="400\tInvalid or empty ID"
else
	#	====================================
	#	Query DB, leggo info
	geterror
fi
output_text
