#!/bin/bash

#  PrestoPRIME  LTFSArchiver
#  Version: 1.0 Beta
#  Authors: L. Savio, L. Boch, R. Borgotallo
#
#  Copyritght (C) 2011-2012 RAI – Radiotelevisione Italiana <cr_segreteria@rai.it>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

. $CFGFILE
. `dirname $0`/common.sh
function output_html
{
echo 'Content-Type: text/html'
echo ''
echo '<HTML><BODY bgcolor="#FFFFCC" link="#000099" vlink="#000099">'
echo '<CENTER>'
if [ ${#dataarray[@]} == 1 ]; then
	echo 'No tape found'
else
	echo '<TABLE border=1>'
	echo '<TR>'
	echo '<TD>Label</TD>'
	echo '<TD>Free MB</TD>'
	echo '<TD>Poolname</TD>'
	echo '<TD>LTOtype</TD>'
	echo '</TR>'
	DATA_IDX=0
	while [ $DATA_IDX -lt ${#dataarray[@]} ]; do
		echo '<TR>'
		echo '<TD>'${dataarray[$DATA_IDX]}'</TD>'
		echo '<TD>'${dataarray[$DATA_IDX+1]}'</TD>'
		echo '<TD>'${dataarray[$DATA_IDX+2]}'</TD>'
		echo '<TD>'${dataarray[$DATA_IDX+3]}'</TD>'
		echo '</TR>'
		let DATA_IDX+=4
	done
	echo '</TABLE></CENTER></BODY></HTML>'
fi
}

################################################################################
# Script starts here
PARM=$QUERY_STRING
pattern=$( get_parameter TapeID )
output=$( get_parameter Output )
poolname=$( get_parameter PoolName )
if [ -z $pattern ]; then
	if [ -z $poolname ]; then
		dataarray=( `$DBACCESS" select label,free,poolname,ltotype from lto_info order by poolname,label;" | tr -d ' ' | tr '|' ' ' | tr '\n' ' '` )
	else
		dataarray=( `$DBACCESS" select label,free,poolname,ltotype from lto_info where poolname='$poolname' order by label;" | tr -d ' ' | tr '|' ' ' | tr '\n' ' '` )
	fi
else
	ppattern='%'$pattern'%'
	if [ -z $poolname ]; then
		dataarray=( `$DBACCESS" select label,free,poolname,ltotype from lto_info where label like '$ppattern' order by poolname, label;" | tr -d ' ' | tr '|' ' ' | tr '\n' ' '` )
	else
		dataarray=( `$DBACCESS" select label,free,poolname,ltotype from lto_info where poolname='$poolname' and label like '$ppattern' order by poolname;" | tr -d ' ' | tr '|' ' ' | tr '\n' ' '` )
	fi
fi
case $output in
	"TEXT")
		if [  -z $dataarray ]; then
			message="400\tNo tape found matching criteria"
		else
			DATA_IDX=0
			message="200"
			while [ $DATA_IDX -lt ${#dataarray[@]} ]; do
				message=$message"\t(${dataarray[$DATA_IDX]},${dataarray[$DATA_IDX+1]},${dataarray[$DATA_IDX+2]},${dataarray[$DATA_IDX+3]})\t"
				let DATA_IDX+=4
			done
		fi
		output_text_common
	;;
	"JSON")
		if [  -z $dataarray ]; then
			message='{"exit_code":"400","message":"No tape found matching criteria"}'
		else
			message='{"exit_code":"200","output":['
			DATA_IDX=0
			LAST_IDX=0
			while [ $DATA_IDX -lt ${#dataarray[@]} ]; do
				let LAST_IDX+=4
				message=$message'{"TapeID":"'${dataarray[$DATA_IDX]}'","FreeSpace":"'${dataarray[$DATA_IDX+1]}'","PoolName":"'${dataarray[$DATA_IDX+2]}'","LTOtype":"'${dataarray[$DATA_IDX+3]}'"}'
				[ $LAST_IDX -lt ${#dataarray[@]} ] && message=$message','
				let DATA_IDX+=4
			done
			message=$message']}'
		fi
		output_json_common
	;;
	*)
		output_html
	;;
esac
