#!/bin/bash

#  PrestoPRIME  LTFSArchiver
#  Version: 0.9 Beta
#  Authors: L. Savio, L. Boch, R. Borgotallo
#
#  Copyritght (C) 2011-2012 RAI – Radiotelevisione Italiana <cr_segreteria@rai.it>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

PARMN=$#
PARMV=( $@ )
while [ `pidof mtx | wc -l` -gt 0 ]; do
	echo "mtx running..."
	sleep 1
done
case ${PARMV[1]} in 
	"/dev/sgx")
		if [ ${PARMV[2]}  == "status" ]; then
			mtx -f /dev/changer status | sed -e 's/VolumeTag=NS/VolumeTag=XX/g' -e 's/VolumeTag = NS/VolumeTag = XX/g'
		else
			PARMV[1]="/dev/changer"
			mtx ${PARMV[@]}
		fi
	;;
	*)
		
		mtx $@
	;;
esac
