#!/bin/bash
#  PrestoPRIME  LTFSArchiver
#  Version: 1.3
#  Authors: L. Savio, L. Boch, R. Borgotallo
#
#  Copyritght (C) 2011-2012 RAI – Radiotelevisione Italiana <cr_segreteria@rai.it>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

function Verify_CheckFile()
{
CHKSMFILE=$( get_parameter ChecksumFile )
if ! [ -f $CHKSMFILE ]; then
        exitcode="400"; message="ChecksumFile supplied: $CHKSMFILE not found"
        FILEPASS="N"
else
        case `head -1 $CHKSMFILE | sed -e 's/^#//'` in
                "MD5"|"SHA1")
                        FILEPASS="Y"
                ;;
                *)
                        exitcode="400"; message="Invalid checksum type supplied: "`head -1 $CHKSMFILE | sed -e 's/^#//'`
                        FILEPASS="N"
                ;;
        esac
fi
}

function insert_write()
{
callingtime=`date '+%Y-%m-%d %H:%M:%S'`
#	's/^\/*//'`
$CMD_DB "INSERT INTO requests ( uuid,status,substatus,manager,operation,sourcefile,callingtime, poolname, datatype, checksum,checksumfile) \
	VALUES ( '$taskid','waiting',0,'$LTFSARCHIVER_MODE','W','$filesrc','$callingtime','$poolname','$itemtype','$ask4checksum','$checksumfile')" > /dev/null 2>&1
RC=$?
}


# Script starts here
. $CFGFILE
. `dirname $0`/common.sh
command=`basename $0`
PARM=$QUERY_STRING
RECEIVEDTIME=`date +'%Y-%m-%dT%H:%M:%S'`
VALIDPARMS="PoolName|Checksum|ChecksumFile|FileName|FromGUI|Output"


output=$( get_parameter Output )
normalize_output
get_supplied_parameters
poolname=$( get_parameter PoolName )		#	PoolName
ask4checksum=$( get_parameter Checksum )	#	Tipo di checksum richiesto
filesrc=$( get_parameter FileName )		#	Nome del file o del folder da archiviare
checksumfile=$( get_parameter ChecksumFile )	#	File con checksum precalcolati
guicall=$( get_parameter FromGUI )		#	true (da parametro nascosto) se arriva da pagina web
test_passed=true
if [ -z $output ]; then
	output=`echo $LTFSARCHIVER_OUTPUT | tr '[A-Z]' ' [a-z]'`
	PARM=$PARM'&Output='$output
fi
#	Eventuali default
if [ -z $poolname ]; then
	poolname=$LTFSARCHIVER_DEFPOOL
	PARM=$PARM'&PoolName='$poolname
fi
if [ -z $ask4checksum ]; then
	ask4checksum="N"
	PARM=$PARM'&Checksum='$ask4checksum
fi
[ -z $guicall ] && guicall=false
if ! [ -z "$BADPARMS" ]; then
        exitcode="400"; message="${BADPARMS}"
	test_passed=false
fi
#==================================================================================
[ -z $guicall ] && guicall=false
if $test_passed; then
	#	C'e' un valore non valido in Checksum - stampo ed esco
	case $ask4checksum in
		"MD5"|"MD5_both"|"SHA1"|"SHA1_both"|"FILE"|"N")
		;;
		*)
			exitcode='400';	message='Invalid Checksum value supplied'
			test_passed=false
		;;
	esac
fi
if $test_passed; then
	#	E' stato passato ChecksumFile ma Checksum diverso da FILE - stampo ed esco
	if ( ! [ -z "$checksumfile" ] && [ "$ask4checksum" != "FILE" ] ); then
		exitcode='400';	message='ChecksumFile supplied but Checksum is not set to FILE'
		test_passed=false
	fi
fi
if $test_passed ; then
	#	E' stato passato ChecksumFile ma Checksum diverso da FILE - stampo ed esco
	if ( [ -z "$checksumfile" ] && [ "$ask4checksum" == "FILE" ] ); then
		exitcode='400';	message='ChecksumFile not supplied but Checksum is set to FILE'
		test_passed=false
	fi
fi
if $test_passed; then
	esiste=`$CMD_DB "SELECT count (*) FROM lto_info WHERE poolname = '$poolname';" | sed -e 's/^\ //' -e 's/\ $//' | head -1`
	if [ $esiste == 0 ]; then
		exitcode='400'; message='Invalid PoolName supplied'
		test_passed=false
	fi
fi
if $test_passed ; then
	#	remove undesired leading multiple slashes
	filesrc=`echo $filesrc | sed 's;^\/*;\/;'`
	if [ -z "$filesrc" ]; then
		exitcode='400';	message='FileName not supplied'
		test_passed=false
	else
		if ( [ -f "$filesrc" ] || [ -d "$filesrc" ] ); then
			[ -f "$filesrc" ] && itemtype="F"
			[ -d "$filesrc" ] && itemtype="D"
			#	se directory elimino eventuale "/" in coda
			[ $itemtype == "D" ] && filesrc=`echo "$filesrc" | sed -e 's;\/$;;'`
		else
			exitcode='400'; message="$filesrc"' not found'
			test_passed=false
		fi
	fi
fi
if $test_passed; then
	if [ "$ask4checksum" == "FILE" ]; then
		Verify_CheckFile
		if [ $FILEPASS == "N" ]; then
			test_passed=false
		fi
	else
		FILEPASS="Y"
	fi
fi
if $test_passed; then
	taskid=`uuidgen`
	#	Insert DB
	insert_write
	if [ $RC == 0 ]; then
		#	restituisco dati
		exitcode="200"
		crea_xml_output
	else
		exitcode='500';	message='Error occurred'
		unset taskid
	fi
fi
crea_xml_answer
send_output
