#!/bin/tcsh -f
#
#  ltfsa_gui
#  Version: 0.0.1
#  Authors: L. Boch
#
#  Copyright (C) 2013-2014 RAI - Radiotelevisione Italiana <cr_segreteria@rai.it>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set echo_style = both
set this = `basename $0`
if ( !($?pdir) ) then
	echo
	echo "$this Error "
	echo "\tVariable 'pdir' must be defined in environment"
	echo
	exit 99
endif
set curloptions = `cat $pdir/config/curloptions`
set ltfsaserverurl = `cat $pdir/config/ltfsaserverurl`
set ltfsaserverurlsav = "$ltfsaserverurl"
#removing /cgi-bin
set ltfsaserverurl = `dirname $ltfsaserverurl`
echo "content-type: text/html\n"
if ( $REQUEST_METHOD != "GET" ) then
	echo "400"
	echo "Bad request "
	echo "$this accept only GET"
	exit 99
endif
set inquery = `echo $QUERY_STRING | cut -d'&' -f1- --output-delimiter=' ' | cut -d'=' -f1- --output-delimiter=' '`
set inquery = `$pdir/bin/clean.querystring $inquery`
set i = 1
while ( $i < $#inquery )
        if ( "$inquery[$i]" == "ltfsaserverurl" ) then
                @ i++
                set ltfsaserverurl = "$inquery[$i]"
		curl $curloptions "$ltfsaserverurl" -o $pdir/logs/$this.$$.out >& $pdir/logs/$this.$$.log
		set ret = $?
		if ( $ret ) then
			echo "403"
			echo "Bad request"
			echo "$this failed on ltfsa service $ltfsaserverurl"
			exit 2
		endif
	else
		echo "400"
		echo "Bad request "
		echo "$this unknown $var=$value"
       	        exit 1
	endif
        @ i++
end
#Modifying config
if ( "$ltfsaserverurl/cgi-bin" != "$ltfsaserverurlsav" ) then
	cp $pdir/config/ltfsaserverurl $pdir/config/ltfsaserverurl.bak
	echo "$ltfsaserverurl/cgi-bin" > $pdir/config/ltfsaserverurl
endif
#Giving form for changing again
set ltfsaserverurlsed = `echo $ltfsaserverurl | sed -e s/'\/'/'\\\/'/g`
cat $pdir/share/ltfsa_gui_config.html | sed -e s/'+++LTFSASERVERURL+++'/$ltfsaserverurlsed/g 
exit 0
