#
#  ltfsa_gui
#  Version: 0.0.1
#  Authors: L. Boch
#
#  Copyright (C) 2013-2014 RAI - Radiotelevisione Italiana <cr_segreteria@rai.it>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
install:
	mkdir logs
	chmod ugo+w logs
	ln -s /home/laurent/Scrivania/prestoprime/ltfsarchiver/github/LTFSArchiver/ltfsa_gui/www/html/ /var/www/html/ltfsa_gui
	ln -s /home/laurent/Scrivania/prestoprime/ltfsarchiver/github/LTFSArchiver/ltfsa_gui/www/cgi-bin/ /var/www/cgi-bin/ltfsa_gui
	ln -s /home/laurent/Scrivania/prestoprime/ltfsarchiver/github/LTFSArchiver/ltfsa_gui/ltfsa_gui-http.conf /etc/apache2/conf.d/ltfsa_gui-http.conf
	chown -h -R laurent /var/www/cgi-bin/ltfsa_gui
	chown laurent.www-data /home/laurent/Scrivania/prestoprime/ltfsarchiver/github/LTFSArchiver/ltfsa_gui/logs
	chmod g+w /home/laurent/Scrivania/prestoprime/ltfsarchiver/github/LTFSArchiver/ltfsa_gui/logs
	chown -R laurent.www-data /home/laurent/Scrivania/prestoprime/ltfsarchiver/github/LTFSArchiver/ltfsa_gui/www/html
	chmod -R g+w /home/laurent/Scrivania/prestoprime/ltfsarchiver/github/LTFSArchiver/ltfsa_gui/www/html
	echo insert the password for user default
	htpasswd -c ltfsa_gui-htpasswords default
	service apache2 reload


uninstall:
	rm /var/www/html/ltfsa_gui
	rm -rf /var/www/cgi-bin/ltfsa_gui
	rm /etc/apache2/conf.d/ltfsa_gui*http.conf
	service apache2 reload


